name: cafeconmiel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - ipykernel
  - ipywidgets
  - jupyterlab
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - seaborn
  - requests
  - beautifulsoup4
  - scikit-learn
  - spacy
  - pip:
    - -r requirements.txt
